classes:
- service.keepalived.cluster.single
- system.linux.system.repo.mcp.openstack
- system.linux.system.repo.mcp.extra
- system.linux.system.repo.saltstack.xenial
- system.linux.system.repo.ubuntu
- system.glusterfs.server.volume.glance
- system.glusterfs.server.volume.keystone
- system.glusterfs.server.cluster
- system.salt.control.virt
- system.salt.control.cluster.opencontrail_analytics_cluster
- system.salt.control.cluster.opencontrail_control_cluster
- system.salt.control.cluster.openstack_control_cluster
- system.salt.control.cluster.openstack_proxy_cluster
- system.salt.control.cluster.openstack_database_cluster
- system.salt.control.cluster.openstack_message_queue_cluster
- system.salt.control.cluster.openstack_telemetry_cluster
- cluster.physical_mcp11_opencontrail.infra
parameters:
  _param:
    cluster_vip_address: ${_param:infra_kvm_address}
    cluster_node01_address: ${_param:infra_kvm_node01_address}
    cluster_node02_address: ${_param:infra_kvm_node02_address}
    cluster_node03_address: ${_param:infra_kvm_node03_address}
    keepalived_vip_interface: br_ctl
    keepalived_vip_virtual_router_id: 69
    deploy_nic: enp3s0f0
    primary_first_nic: enp3s0f1
    primary_second_nic: enp5s0f0
  salt:
    control:
      size: #RAM 4096,8192,16384,32768,65536
      ##Default production sizing
        openstack.control:
          cpu: 8
          ram: 8192
          disk_profile: small
          net_profile: default
        openstack.database:
          cpu: 6
          ram: 8192
          disk_profile: large
          net_profile: default
        openstack.message_queue:
          cpu: 6
          ram: 8192
          disk_profile: small
          net_profile: default
        openstack.telemetry:
          cpu: 6
          ram: 4096
          disk_profile: xxlarge
          net_profile: default
        openstack.proxy:
          cpu: 4
          ram: 2048
          disk_profile: small
          net_profile: default
        opencontrail.control:
          cpu: 8
          ram: 8192
          disk_profile: small
          net_profile: opencontrail
        opencontrail.analytics:
          cpu: 8
          ram: 8192
          disk_profile: large
          net_profile: default
      cluster:
        internal:
          node:
            prx02:
              provider: kvm03.${_param:cluster_domain}
            mdb01:
              image: ${_param:salt_control_xenial_image}
            mdb02:
              image: ${_param:salt_control_xenial_image}
            mdb03:
              image: ${_param:salt_control_xenial_image}
            ctl01:
              image: ${_param:salt_control_xenial_image}
            ctl02:
              image: ${_param:salt_control_xenial_image}
            ctl03:
              image: ${_param:salt_control_xenial_image}
            dbs01:
              image: ${_param:salt_control_xenial_image}
            dbs02:
              image: ${_param:salt_control_xenial_image}
            dbs03:
              image: ${_param:salt_control_xenial_image}
            msg01:
              image: ${_param:salt_control_xenial_image}
            msg02:
              image: ${_param:salt_control_xenial_image}
            msg03:
              image: ${_param:salt_control_xenial_image}
            prx01:
              image: ${_param:salt_control_xenial_image}
            prx02:
              image: ${_param:salt_control_xenial_image}
  virt:
    nic:
      default:
        eth1:
          bridge: br_mgm
        eth0:
          bridge: br_ctl
      opencontrail:
        - name: eth0
          bridge: br_mgm
          model: virtio
        - name: eth1
          bridge: br_ctl
          model: virtio
        - name: eth2
          bridge: br_data
          model: virtio
  linux:
    network:
      interface:
        eth0:
          enabled: true
          type: eth
          proto: manual
          name: ${_param:deploy_nic}
        eth1:
          enabled: true
          type: slave
          proto: manual
          name: ${_param:primary_first_nic}
          master: bond0
        eth2:
          enabled: true
          type: slave
          proto: manual
          name: ${_param:primary_second_nic}
          master: bond0
        br_mgm:
          enabled: true
          proto: static
          type: bridge
          address: ${_param:deploy_address}
          netmask: 255.255.255.192
          gateway: 172.17.32.193
          name_servers:
          - 8.8.8.8
          - 8.8.4.4
          use_interfaces:
          - ${_param:deploy_nic}
        bond0:
          enabled: true
          proto: manual
          type: bond
          use_interfaces:
          - ${_param:primary_first_nic}
          - ${_param:primary_second_nic}
          slaves: ${_param:primary_first_nic} ${_param:primary_second_nic}
          mode: active-backup
        bond0.2428:
          enabled: true
          proto: manual
          type: vlan
          use_interfaces:
          - bond0
        bond0.2429:
          enabled: true
          proto: manual
          type: vlan
          use_interfaces:
          - bond0
        br_ctl:
          enabled: true
          type: bridge
          proto: static
          address: ${_param:single_address}
          netmask: 255.255.255.0
          use_interfaces:
          - bond0.2428
        br_data:
          enabled: true
          type: bridge
          proto: manual
          use_interfaces:
          - bond0.2429
    system:
      package:
        linux-image-4.8.0-39-generic:
          version: latest
        linux-headers-4.8.0-39-generic:
          version: latest
        linux-image-extra-4.8.0-39-generic:
          version: latest
        linux-headers-4.8.0-39:
          version: latest
      user:
        root:
          enabled: true
          name: root
          home: /root
          # Password is cloudlab, comment out, configure your SSH key bellow
          # and disable password auth
          password: $6$0Qqj.6l.$T9k9Onm9pIDo6ULABVBRNogyizG.9CnwQ4bvI4xH.AWeIGHbLyFU87ejMTtKvAAyd3dncRYbeUV.VbnXJU2u./
